### PR TITLE
Make role work for chroot images

### PR DESCRIPTION
**Pull request by jabl**

### CODE REVIEW

**Comment by lae** [comment]
tests are failing here because the test suite is out of date/isn't pinned to an older version: 
https://github.com/lae/ansible-role-travis-lxc/releases/tag/v0.7.0 (pin to 0.7.3 as that's the last in the 0.7.x series)
cc @martbhell

**Comment by martbhell** [comment]
Thank you, 

TIL one can do this to install a specific version:

``` bash
$ ansible-galaxy install lae.travis-lxc,v0.7.3
```

Unfortunately it doesn't seem to help @lae . All builds appear to fail, in different ways..

The ubuntus seems to be stuck in
```
"TASK [lae.travis-lxc : Wait for base containers to finish bootstrapping] "

**Comment by lae** [comment]
@martbhell Looking at the build I'm not seeing what you're seeing? Looks like they all start up and run your role, except for the CentOS 6 one - and that one looks like it's related to https://github.com/lae/ansible-role-travis-lxc/issues/26, which is fixed in 0.8.0.

**Comment by martbhell** [comment]
@lae ah, I gave up when it took longer than 5 minutes to run the build. The Ubuntu ones completed after 15-20min. 10min or 591s was from installing the packages. So something else took 6-8 minutes.

The CentOS7 build fails with this (from error field of the output) which looks like a yum repo error too, so it might be OK to have a failure. If so I would want to hear if this passes currently on real hardware:

<pre>
Error: Package: 3:dkms-nvidia-410.79-1.el7.x86_64 (nvidia)
           Requires: dkms\nError: Package: 3:nvidia-driver-cuda-410.79-1.el7.x86_64 (nvidia)
           Requires: ocl-icd\nError: Package: 3:nvidia-driver-410.79-1.el7.x86_64 (nvidia)
           Requires: libva-vdpau-driver(x86-64)\nError: Package: 3:nvidia-driver-cuda-410.79-1.el7.x86_64 (nvidia)
           Requires: opencl-filesystem
</pre>

**Comment by lae** [comment]
Yeah, that looked like a separate issue. I'm no longer at FireEye so I don't quite have hardware to test with, unfortunately.

Container builds will generally take ~10 minutes to complete pulling/debootstrap/etc, it's a little bit faster on subsequent runs because they're cached (as much as they can be) after the initial run (which is per branch). Hopefully I can make this faster with image-based builds when moving to LXD on Xenial later though.

**Comment by jabl** [comment]
Do you mean the role itself on real hardware, or the testsuite? Role works, yes, haven't tried the testsuite. Is there some easy way to run it outside travis?

**Comment by martbhell** [comment]
I meant this role (this PR) on real hardware with GPU. Travis just runs some syntax check and the playboon in tests/test.yml. If your test is same as that then I guess one could call that running travis locally :)

Any comments on why it fails for EL7?

**Comment by VilleS1** [comment]
Any suggestions what to do with these tests failing?

**Comment by jabl** [comment]
Since pinning it to 0.7.3 apparently didn't work, I guess the next thing to try would be to port it to the latest travix-lxc. But I think that should be separate from this PR.

(We use this role with this PR to setup our OpenHPC GPU nodes, so yes, it works.)

**Comment by VilleS1** [comment]
I'll just merge it.

**Pull request merged**
