### PR TITLE
Test suite cleanup using LXC

### PR DESCRIPTION
**Pull request by lae**
Cleaned up the Travis tests here to make it simpler for me to add tests for other distros in preparations for adding support for more distributions.

### CODE REVIEW

**Comment by lae** [comment]
Also removed `cuda_packages: "traceroute"` as part of the test because it's not really testing CUDA installation if CUDA doesn't get installed, but you can change that back if you want.

TODO is to re-add the test against ansible-devel.

Setting cuda_init to false skips a few tasks, but starting the actual service fails because the CI environment does not have an nvidia device. Could try to resolve this by just enabling the service in one step and then a handler to start the service (with a variable toggle to skip it that we could use during the test). Thoughts?

**Comment by martbhell** [comment]
Nice! Haven't used LXC before, it looks a lot cleaner.
I think a handler would be good for this cuda_init.service.
How does my commit look?

**Comment by lae** [comment]
There needs to be a default for `cuda_init_restart_service` set for this I believe.

**Comment by lae** [comment]
Okay, this looks good to me.

**Pull request merged**
