### PR TITLE
Use lae.travis-lxc and bandage avahi issue (fixing #11)

### PR DESCRIPTION
**Pull request by lae**
This simplifies the test suite a bit more.

### CODE REVIEW

**Comment by lae** [comment]
Need to restart the cent6 build since it looks like it didn't get an IP in time (will look into this more later).

Actually, looks like it didn't pass, will look into it more when I get a chance.

**Comment by martbhell** [comment]
I restarted both CentOS7 (this failed idempotency test because of too slow mirror or something like that) but also the CentOS6 one.

**Comment by martbhell** [comment]
CentOS7 passed after restart. CentOS6 failed again

**Comment by lae** [comment]
Pushed an update to lae.travis-lxc for checking network connectivity differently, so the cent6 build should pass without issue (well, if the cuda repo doesn't time out). Just made that last commit for semantic reasons and to start another build.

**Comment by lae** [comment]
Yeah it looks like the cent6 build failed on getting packages from the cuda repo this time (passed here: https://travis-ci.org/lae/ansible-role-cuda/jobs/199816622)

**Comment by martbhell** [comment]
Same for CentOS7 after restarts - looks like cuda 8.0.61 was released last night.
I'll just wait a few days and try again. Thanks!

**Comment by martbhell** [comment]
Merged. CentOS6 test play failed on the first run but succeeded/changed on the idempotency test.

**Pull request merged**
