### PR TITLE
Add Ubuntu 20.04 support

### PR DESCRIPTION
**Pull request by easybe**

### CODE REVIEW

**Comment by easybe** [comment]
@VilleS1 could you maybe have a look at this simple patch? There is an Ubuntu 20.04 APT repo now: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/

**Comment by VilleS1** [comment]
Merged. I didn't notice this patch before.

**Comment by easybe** [comment]
Cool, thank you very much @VilleS1. What is the process for getting this into Ansible Galaxy? The version there is still v1.6.7 which is almost one year old.

**Comment by VilleS1** [comment]
I don't know.

**Comment by easybe** [comment]
I suspect that the reason is the missing Travis CI job: https://travis-ci.org/CSCfi/ansible-role-cuda
Anything we can do about that?

**Comment by VilleS1** [comment]
Might be. But you have the wrong url, the home of the role has changed:
https://travis-ci.org/github/fgci-org/ansible-role-cuda

There are some errors in the build.

**Comment by easybe** [comment]
Here a shot at fixing that: https://github.com/fgci-org/ansible-role-cuda/pull/35

**Comment by VilleS1** [comment]
I got travis build already working. But since the role is now in different organisation the build status does not update to Galaxy CSCfi. It should update to fgci-org. I am not sure how to do that. Do you know?

**Comment by easybe** [comment]
I see that your colleagues have struggled with the same in the past: https://github.com/ansible/galaxy/issues/42

**Comment by easybe** [comment]
Is removing the role and re-adding it under from the new GH org an option? Otherwise I guess you have to get the Ansible people to move it (as I see you requested [here](https://github.com/ansible/galaxy/issues/42#issuecomment-793524959) already).

**Comment by VilleS1** [comment]
Yes, that is what I am trying to do.

**Comment by VilleS1** [comment]
ansible-role-cuda is now in galaxy under fgci.

**Comment by easybe** [comment]
Should it not be `fcgi.cuda` analogous to `cscfi.cuda` instead of `fgci.ansible_role_cuda` ?

**Comment by VilleS1** [comment]
Yes, that is now fixed too.

**Comment by easybe** [comment]
Cool, thank you very much!

**Comment by easybe** [comment]
~~Maybe you also want to update the "OS Platforms" tags in Galaxy. E.g. Ubuntu 20.04 is `focal` (https://wiki.ubuntu.com/Releases).~~

Never mind, https://github.com/fgci-org/ansible-role-cuda/pull/36.

**Comment by easybe** [comment]
Never mind, https://github.com/fgci-org/ansible-role-cuda/pull/36.

**Pull request merged**
